const companyTypes = {
  FETCH_COMPANY_REQUEST: 'FETCH_COMPANY_REQUEST',
  FETCH_COMPANY_SUCCESS: 'FETCH_COMPANY_SUCCESS',
  FETCH_COMPANY_FAILURE: 'FETCH_COMPANY_FAILURE',
};

export default companyTypes;
